### ISSUE TITLE
Does the tool support scanning maven dependencies?

### ISSUE THREAD

**Issue by hhr-tj-nk** [adoptium/emt4j#3]
Use the EMT4J command-line tool    0.2

I tried to use this tool to scan the spring boot application jar package  (from jdk8 to jdk17).
It seems that there is no dependency scanning, because there is a dependency( hbase-client 1.3.1 ) in my application that does not support jdk17.

**Comment by lingjun-cg** [comment]
Is it a fat jar(uber jar)? EMT4J now not support scan fat jar. The next release will support fat jar. If you want to scan now,you can unzip the spring boot application jar to a temporary directory ,then scan the temporary directory

**Comment by hhr-tj-nk** [comment]
Thank you very much. I'll try it after unzip it
