### ISSUE TITLE
Ask: Do only static checks need to be performed?

### ISSUE THREAD

**Issue by zyxxoo** [adoptium/emt4j#36]
I'm a little confused about static and runtime checking, do I just need to do either one?

**Comment by D-D-H** [comment]
Hi,
You can enable both of them or one of them. Runtime checking can find some problems hard to find for static analysis.

To perform runtime checking, there are two ways:

1. By java agent. [Download address](https://mvnrepository.com/artifact/org.eclipse.emt4j/emt4j-agent-jdk8)

2. By maven plugin, please refer to the README
