### ISSUE TITLE
Not a valid fromVersion: 11,toVersion:21 pair!

### ISSUE THREAD

**Issue by immadolf** [adoptium/emt4j#56]
<img width="936" alt="image" src="https://github.com/adoptium/emt4j/assets/12369197/9cf22a6b-1946-4689-87eb-428b0bd6ba78">
As shown in the figure, the document states that 11 and 21 are supported configurations, but when actually used, it prompts `Not a valid fromVersion: 11,toVersion:21 pair!`

This is my pom configuration:
```xml
            <plugin>
                <groupId>org.eclipse.emt4j</groupId>
                <artifactId>emt4j-maven-plugin</artifactId>
                <version>0.8.0</version>
                <executions>
                    <execution>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <fromVersion>11</fromVersion>
                    <toVersion>21</toVersion>
                    <outputFile>report.html</outputFile>
                </configuration>
            </plugin>

```

**Comment by D-D-H** [comment]
@immadolf 
21 is not supported by 0.8.0.
Please try to install the latest code locally.

**Comment by immadolf** [comment]
OK, thank you, but since 0.8.0 does not support 21 yet, is it misleading in the readme document? @D-D-H

**Comment by D-D-H** [comment]
Yes. I'll add a description to clarify it.

**Comment by D-D-H** [comment]
README is updated.

We'll release 0.9 as soon as possible.

**Comment by immadolf** [comment]
Thank you for the clarification and the prompt update. I appreciate your efforts in addressing the issue. I look forward to the release of version 0.9.

**Comment by BrayanMnz** [comment]
0.9 was never released? @D-D-H
