### ISSUE TITLE
Please publish emt4j-maven-plugin to The Central Repository

### ISSUE THREAD

**Issue by diguage** [adoptium/emt4j#6]
Please publish emt4j-maven-plugin to The Central Repository

**Comment by lingjun-cg** [comment]
Publish to central repository need some time. If you eager to use it, you can publish to local or your company's private repository if it exist.

**Comment by SuperBaBa** [comment]
我来试试 publish

**Comment by lingjun-cg** [comment]
EMT4J is a tool that help checking incompatible code. Publish a tool to maven central repository seems a little usefulness. 
So if you want to use the maven plugin, I recommend publish to local repository or company's private repository. 
If this solution not meet your requirement, using the EMT4J command line is better.

**Comment by diguage** [comment]
> EMT4J is a tool that help checking incompatible code. Publish a tool to maven central repository seems a little usefulness. So if you want to use the maven plugin, I recommend publish to local repository or company's private repository. If this solution not meet your requirement, using the EMT4J command line is better.

Publish emt4j-maven-plugin to The Central Repository is more convenient for everyone to use.
