### ISSUE TITLE
当在windows平台运行时帮助信息会显示“Usage:analysis.sh”

### ISSUE THREAD

**Issue by SuperBaBa** [adoptium/emt4j#7]
增加了一个平台辨别的条件
```java
String osName = System.getProperties().getProperty("os.name");
if (osName.equals("Linux")) {
    System.err.print("Usage:analysis.sh ");
} else {
    System.err.print("Usage:analysis.bat ");
}
```

**Comment by lingjun-cg** [comment]
Fixed.  Add the following in method org.eclipse.emt4j.analysis.AnalysisMain#printUsage.
`      String osName = System.getProperty("os.name");
        boolean windows = osName != null && osName.toLowerCase().indexOf("windows") != -1;
        String launcher = windows ? "analysis.bat" : "analysis.sh";
        System.err.println("Usage:" + launcher + " [-f version] [-t version] [-p txt] [-o outputfile] [-j target jdk home] [-v] <files>");`
